# Configuration of MQTT devices to be bridged

#pin = "10340567"
broker = "192.168.1.22:1883"
bridgename = "MacMQTTBridge"

[[devices.temperaturesensor]]
displayname = "Balcony Temperature"
topic = "home/balcony/temp"

[[devices.temperaturesensor]]
displayname = "Bedroom Temperature"
topic = "home/bedroom/temp"

[[devices.temperaturesensor]]
displayname = "Lounge Temperature"
topic = "home/lounge/temp"

[[devices.lightsensor]]
displayname = "Balcony Light"
topic = "home/balcony/light"

[[devices.lightsensor]]
displayname = "Bedroom Light"
topic = "home/bedroom/light"

[[devices.lightsensor]]
displayname = "Lounge Light"
topic = "home/lounge/light"

  # [[pressuresensor]]
  # displayname = "Barometric Pressure"
  # topic = "home/lounge/pressure"
  #
  # [[windSensor]]
  # displayname = "Falkner Beacon"
  # topic = "bom/falkner/windspeed"
  #
  # [[windSensor]]
  # displayname = "St Kilda"
  # topic = "bom/stkilda/windspeed"
  #
  # [[windSensor]]
  # displayname = "South Channel"
  # topic = "bom/southchannel/windspeed"
