# Configuration of MQTT devices to be bridged

broker = "192.168.1.22:1883"

[[temperaturesensor]]
displayname = "Balcony Temperature"
topic = "home/balcony/temp"

[[temperaturesensor]]
displayname = "Bedroom Temperature"
topic = "home/bedroom/temp"

[[temperaturesensor]]
displayname = "Lounge Temperature"
topic = "home/lounge/temp"

[[lightsensor]]
displayname = "Balcony Light"
topic = "home/balcony/light"

[[lightsensor]]
displayname = "Bedroom Light"
topic = "home/bedroom/light"

[[lightsensor]]
displayname = "Lounge Light"
topic = "home/lounge/light"

[[pressuresensor]]
displayname = "Barometric Pressure"
topic = "home/lounge/pressure"

[[windSensor]]
displayname = "Falkner Beacon"
topic = "bom/falkner/windspeed"

[[windSensor]]
displayname = "St Kilda"
topic = "bom/stkilda/windspeed"

[[windSensor]]
displayname = "South Channel"
topic = "bom/southchannel/windspeed"
